CREATE TABLE Item (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Guid UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(126) NOT NULL,
    Description NVARCHAR(500) NOT NULL,
    Price DECIMAL(18, 2) NOT NULL,
    SKU NVARCHAR(MAX),
    CreatedOn DATETIME NOT NULL,
    LastModification DATETIME NULL
);