CREATE TABLE Stock (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Guid UNIQUEIDENTIFIER NOT NULL,
    QuantityType INT NOT NULL, 
    Quantity INT NOT NULL,
    Location NVARCHAR(50) NULL,
    ItemId INT NOT NULL,
    FOREIGN KEY (ItemId) REFERENCES Item(Id) ON DELETE CASCADE
);
